pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'horsing-around'

// Optional add-on: RDR2-style over-the-shoulder third-person camera (separate mod, separate jar).
include 'shoulder-cam'
